// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func SearchBar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div style=\"display: block; margin: 0 auto; padding-top: 10px;\"><input class=\"form-control\" type=\"search\" name=\"search\" placeholder=\"Type tags you are intrested...\" hx-post=\"/tag\" hx-trigger=\"input changed delay:500ms, search\" hx-target=\"#search-results\" hx-indicator=\".htmx-indicator\" style=\"width: 300px;\"><table class=\"table\"><thead><tr><th>tags</th></tr></thead> <tbody id=\"search-results\"></tbody></table></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func Main() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"pl\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"https://unpkg.com/htmx.org@1.9.11\" integrity=\"sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0\" crossorigin=\"anonymous\"></script><title>Moja Strona</title><style>\r\n        body {\r\n            margin: 0;\r\n            padding: 0;\r\n            font-family: Arial, sans-serif;\r\n            background-color: #e6e6ff; /* ciemniejszy niebieski */\r\n            display: flex;\r\n            flex-direction: column;\r\n            min-height: 100vh;\r\n        }\r\n\r\n        header, footer {\r\n            background-color: #85a3ff; /* jasny niebieski */\r\n            color: #ffffff; /* biały tekst */\r\n            padding: 10px;\r\n            height: 6vh;\r\n        }\r\n\r\n        footer {\r\n            background-color: #4d68b8; /* ciemniejszy niebieski */\r\n            height: 6vh;\r\n        }\r\n\r\n        #major {\r\n        width: 100%;\r\n        border: 1px solid black;\r\n        }\r\n\r\n    #one {\r\n        width: auto;\r\n        float: left;\r\n        background-color: #caddfc;\r\n        height: 80vh;\r\n        width: 10vh;\r\n    }\r\n\r\n    #two {\r\n        width:auto;\r\n        padding-left: 90px;\r\n        min-width:100%;\r\n        background-color: #deeafc;\r\n        height: 80vh;\r\n        width: 80vh;\r\n    }\r\n    #bottom{\r\n        width: 100vh;\r\n        background-color: #8f9eb5;\r\n    }\r\n\r\n    </style></head><body><header><h1>Board</h1></header><main id=\"major\"><div id=\"one\">Hello</div><div id=\"two\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SearchBar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div id=\"bottom\">TU cos</div></main><footer>Autor: MK\r</footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
